### ISSUE TITLE
endcsname, fancyhdr

### ISSUE THREAD

**Issue by kevin335200** [zinnjonas/ukon-infie#30]
MWE:
\documentclass{scrartcl}
\usepackage[lang=de]{ukon-infie}
\renewcommand{\sc}{\textsc}
\renewcommand{\bf}{\textbf}
\Names{Your Name}
\Lecture[FOO]{Foobar}
\Term{WS 1970/1971}     
\begin{document}
    \begin{ukon-infie}[01.01.1970]{42}
        \begin{exercise}[p=10.7]{Title of Exercise}
            \question{Question to be answered?}{
            Answer here.
            }
        \end{exercise}
        \begin{exercise}[p=10]{Title of Exercise}
        Content of Exercise
        \end{exercise}
    \end{ukon-infie}
\end{document}

log:
  | untitled-1.tex | 9 | Missing \endcsname inserted.<to be read again>                    \aftergroup l.9     \begin{ukon-infie}{42}
-- | -- | -- | --
  | ukon-infie.sty | 101 | Class scrartcl Warning: Usage of package `fancyhdr' together with a KOMA-Script class is not recommended. I'd suggest to use package `scrlayer' or `scrlayer-scrpage', because they support KOMA-Script classes. With `fancyhdr' several features of class `scrartcl' like options `headsepline', `footsepline' or command `\MakeMarkcase' and the commands `\setkomafont' and `\addtokomafont' for the page style elements need explicite user intervention to work. Nevertheless, using requested package `fancyhdr' on input line 101.

**Comment by zinnjonas** [comment]
It is just a warning so far. And the not KOMA class like article are working fine.
So maybe use them or feel free to rework the fancy dynamic footer to the KOMA layers.

Can not promise to investigate the time.
